server:
  port: 8880

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/dilanyilmaz/microservice-e-itim-config-server.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "dilanyilmaz"
          password: ${GIT_KEY}
